name: E2E Testing

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      - uses: actions/cache@v3
        id: gatsby-cache
        env:
          files: >-
            ${{ hashFiles('www/gatsby-config.ts', 'www/gatsby-node.ts') }}
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-${{ env.files }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-
      - name: Install dependencies
        uses: ./.github/actions/yarn-install
      - name: Install Playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install chromium --with-deps
      - name: Build Gatsby Site
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
          IS_PLAYWRIGHT: true
      - name: Run Playwright
        run: yarn e2e:build